from .tt_website_path_urls import *
from .tt_website_report_urls import *
from .tt_website_train_urls import *
from .tt_website_airline_urls import *
from .tt_website_ppob_urls import *
from .tt_website_registration_urls import *
from .tt_website_visa_url import *
from .tt_website_passport_url import *
from .tt_website_issued_offline_urls import *
from .tt_website_activity_urls import *
from .tt_website_tour_urls import *
from .tt_website_hotel_urls import *
from .tt_website_event_urls import *
from .tt_website_bus_urls import *
from .tt_website_medical_global_urls import *
from .tt_website_swab_express_urls import *
from .tt_website_mitra_keluarga_urls import *
from .tt_website_lab_pintar_urls import *
from .tt_website_sentra_medika_urls import *
from .tt_website_insurance_urls import *
from .tt_website_group_booking_urls import *
from .tt_website_medical_urls import * #PALING BAWAH KARENA ADA PATH DYNAMIC PHC/PERIKSAIN
from .tt_website_urls import *
